version: "3"
services:
  ui:
    image: node:16.17.0
    # tty: true
    volumes:
      - ./ui:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
  api:
    # image: python:slim
    # tty: true
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
